# Generated by Django 5.2.12 on 2026-03-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='veiculo',
        ),
    ]
