# Generated by Django 5.2.12 on 2026-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='categoria',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Tablet', 'Tablet'), ('Notebook', 'Notebook'), ('Outros', 'Outros')], default='Celular', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaoativo',
            name='categoria',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Tablet', 'Tablet'), ('Notebook', 'Notebook'), ('Outros', 'Outros')], default='Celular', max_length=50),
        ),
    ]
