# Generated by Django 5.2.12 on 2026-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_agendamento_passageiros_agendamento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoativo',
            name='assinatura',
            field=models.CharField(blank=True, null=True),
        ),
    ]
