# Generated by Django 5.2.12 on 2026-04-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_agendamento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.veiculo', verbose_name='Veículo'),
        ),
    ]
