# Generated by Django 5.2.12 on 2026-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_ativo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='empresa',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='assinatura_checkout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checkout_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='foto_checkout',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_viagens/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacao_checkout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='quilometragem_checkout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
