# Generated by Django 5.2.12 on 2026-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_solicitacaoativo_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoativo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
