# Generated by Django 5.2.12 on 2026-04-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_agendamento_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/%Y/%m/%d/'),
        ),
    ]
