# Generated by Django 5.2.12 on 2026-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_profile_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='foto_checkout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
