# Generated by Django 5.2.12 on 2026-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_veiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='passageiros',
            field=models.IntegerField(default=1),
        ),
    ]
