# Generated by Django 5.2.12 on 2026-05-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_agendamento_foto_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Motorola', 'Motorola'), ('Xiaomi', 'Xiaomi'), ('Lenovo', 'Lenovo'), ('Outros', 'Outros')], default='Lenovo', max_length=100),
        ),
    ]
