# Generated by Django 5.2.12 on 2026-05-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_ativo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Motorola', 'Motorola'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei'), ('Google', 'Google'), ('Realme', 'Realme'), ('OnePlus', 'Oneplus'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Asus', 'Asus'), ('Nokia', 'Nokia'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('HP', 'Hp'), ('Vaio', 'Vaio'), ('LG', 'Lg'), ('Sony', 'Sony'), ('Electrolux', 'Electrolux'), ('Brastemp', 'Brastemp'), ('Consul', 'Consul'), ('Panasonic', 'Panasonic'), ('Midea', 'Midea'), ('Philco', 'Philco'), ('Britânia', 'Britania'), ('TCL', 'Tcl'), ('Arno', 'Arno'), ('Mondial', 'Mondial'), ('Black+Decker', 'Black Decker'), ('Philips', 'Philips'), ('Hamilton Beach', 'Hamilton Beach'), ('Faet', 'Faet'), ('Outros', 'Outros')], default='Lenovo', max_length=100),
        ),
    ]
