# Generated by Django 5.2.12 on 2026-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_ativo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Lenovo', 'Lenovo'), ('Motorola', 'Motorola'), ('Xiaomi', 'Xiaomi'), ('Huawei', 'Huawei'), ('Google', 'Google'), ('Realme', 'Realme'), ('OnePlus', 'Oneplus'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Asus', 'Asus'), ('Nokia', 'Nokia'), ('Dell', 'Dell'), ('Epson', 'Epson'), ('Acer', 'Acer'), ('HP', 'Hp'), ('Vaio', 'Vaio'), ('LG', 'Lg'), ('Sony', 'Sony'), ('TCL', 'Tcl'), ('Philips', 'Philips'), ('Jabra', 'Jabra'), ('Poly', 'Poly'), ('EPOS', 'Epos'), ('Logitech', 'Logitech'), ('Kensington', 'Kensington'), ('3M', 'Tr M'), ('Anker', 'Anker'), ('StarTech.com', 'Startech'), ('Belkin', 'Belkin'), ('Outros', 'Outros')], default='Lenovo', max_length=100),
        ),
    ]
