# Generated by Django 5.2.12 on 2026-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_veiculo_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(max_length=200)),
                ('apolice', models.IntegerField(default=1)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('plano', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='versao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
