# Generated by Django 5.2.12 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_ativo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='marca',
            field=models.CharField(choices=[('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Epson', 'Epson'), ('Google', 'Google'), ('HP', 'Hp'), ('Huawei', 'Huawei'), ('Jabra', 'Jabra'), ('Kensington', 'Kensington'), ('Lenovo', 'Lenovo'), ('LG', 'Lg'), ('Logitech', 'Logitech'), ('Motorola', 'Motorola'), ('Nokia', 'Nokia'), ('OnePlus', 'Oneplus'), ('Oppo', 'Oppo'), ('Philips', 'Philips'), ('Realme', 'Realme'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('TCL', 'Tcl'), ('Vaio', 'Vaio'), ('Vivo', 'Vivo'), ('Xiaomi', 'Xiaomi'), ('Outros', 'Outros')], default='Lenovo', max_length=100),
        ),
    ]
