# Generated by Django 5.2.12 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_seguro_veiculo_chassi_veiculo_cor_veiculo_renavam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguro',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='apolice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='inicio_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='plano',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='seguro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
