# Generated by Django 5.2.12 on 2026-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_ativo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='categoria',
            field=models.CharField(choices=[('Celular', 'Celular'), ('Tablet', 'Tablet'), ('Notebook', 'Notebook'), ('Outros', 'Outros')], default='Celular', help_text='Selecione a categoria', max_length=50),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='conta_google',
            field=models.CharField(blank=True, default='', help_text='Opcional', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='marca',
            field=models.CharField(choices=[('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Epson', 'Epson'), ('Google', 'Google'), ('HP', 'Hp'), ('Huawei', 'Huawei'), ('Jabra', 'Jabra'), ('Kensington', 'Kensington'), ('Lenovo', 'Lenovo'), ('LG', 'Lg'), ('Logitech', 'Logitech'), ('Motorola', 'Motorola'), ('Nokia', 'Nokia'), ('OnePlus', 'Oneplus'), ('Oppo', 'Oppo'), ('Philips', 'Philips'), ('Realme', 'Realme'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('TCL', 'Tcl'), ('Vaio', 'Vaio'), ('Vivo', 'Vivo'), ('Xiaomi', 'Xiaomi'), ('Outros', 'Outros')], default='Lenovo', help_text='Selecione a marca', max_length=100),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='modelo',
            field=models.CharField(help_text='Selecione o modelo', max_length=100),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='numero_de_serie',
            field=models.CharField(help_text='Ex: SN123456789', max_length=100),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='senha_conta_google',
            field=models.CharField(blank=True, default='', help_text='Opcional', max_length=255, null=True),
        ),
    ]
