# Generated by Django 5.2.12 on 2026-04-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_delete_seguro_veiculo_apolice_veiculo_fim_vigencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='apolice',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='fim_vigencia',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='seguro',
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(max_length=100)),
                ('plano', models.CharField(max_length=100)),
                ('num_apolice', models.IntegerField(default=1)),
                ('inicio_vigencia', models.DateTimeField()),
                ('final_vigencia', models.DateTimeField()),
                ('apolice', models.ImageField(blank=True, null=True, upload_to='veiculos/%Y/%m/%d/')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.veiculo', verbose_name='Veículo')),
            ],
        ),
    ]
