# Generated by Django 5.2.12 on 2026-05-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_agendamento_data_partida_real_alter_ativo_categoria_and_more'),
        ('scheduling', '0009_alter_ativo_categoria_alter_ativo_conta_google_and_more'),
    ]

    operations = [
    ]
