# Generated by Django 5.2.12 on 2026-05-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_agendamento_data_partida_real_alter_ativo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
