# Generated by Django 5.2.12 on 2026-05-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_veiculo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=150)),
                ('local', models.CharField(max_length=150)),
                ('quilometragem', models.IntegerField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='scheduling.veiculo')),
            ],
        ),
    ]
