# Generated by Django 5.2.12 on 2026-05-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_veiculo_foto'),
        ('scheduling', '0010_merge_20260526_1121'),
    ]

    operations = [
    ]
