# Generated by Django 5.2.12 on 2026-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_remove_veiculo_apolice_remove_veiculo_fim_vigencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguro',
            name='plano',
        ),
        migrations.AlterField(
            model_name='seguro',
            name='seguro',
            field=models.CharField(max_length=200),
        ),
    ]
