# Generated by Django 5.2.12 on 2026-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_remove_seguro_plano_alter_seguro_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=350)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
