# Generated by Django 5.2.12 on 2026-05-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_merge_20260528_1720'),
        ('scheduling', '0011_revisao'),
    ]

    operations = [
    ]
