# Generated by Django 5.2.12 on 2026-06-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_agendamento_usuario_checkout'),
        ('scheduling', '0012_merge_0011_merge_20260528_1720_0011_revisao'),
    ]

    operations = [
    ]
