# Generated by Django 5.2.12 on 2026-04-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='texto',
            new_name='mensagem',
        ),
    ]
