# Generated by Django 5.2.12 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_agendamento_usuario_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisao',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
