# Generated by Django 5.2.12 on 2026-06-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_merge_20260602_1146'),
        ('scheduling', '0013_revisao_descricao'),
    ]

    operations = [
    ]
