# Generated by Django 5.2.12 on 2026-04-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_rename_texto_info_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.veiculo'),
        ),
    ]
