# Generated by Django 5.2.12 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_merge_0013_merge_20260602_1146_0013_revisao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_manutencao',
            field=models.BooleanField(default=False),
        ),
    ]
