# Generated by Django 5.2.12 on 2026-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_info_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='apolice',
            field=models.FileField(blank=True, null=True, upload_to='seguros/'),
        ),
    ]
