# Generated by Django 5.2.12 on 2026-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_agendamento_is_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_checkout_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
