# Generated by Django 5.2.12 on 2026-04-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_informacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='texto',
            new_name='mensagem',
        ),
    ]
