# Generated by Django 5.2.12 on 2026-04-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_rename_texto_informacao_mensagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Informacao',
        ),
    ]
