# Generated by Django 5.2.12 on 2026-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Celular', 'Celular'), ('Tablet', 'Tablet'), ('Notebook', 'Notebook')], default='Celular')),
                ('modelo', models.CharField()),
                ('numero_de_serie', models.CharField()),
            ],
        ),
    ]
