# Generated by Django 5.2.12 on 2026-04-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='marca',
            field=models.CharField(default=''),
        ),
    ]
