# Generated by Django 5.2.12 on 2026-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_solicitacaoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
    ]
