# Generated by Django 5.2.12 on 2026-04-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0024_ativo_emprestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativo',
            old_name='emprestado',
            new_name='disponibilidade',
        ),
    ]
