# Generated by Django 5.2.12 on 2026-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0026_ativo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoativo',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
