# Generated by Django 5.2.12 on 2026-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_alter_solicitacaoativo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoativo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
