# Generated by Django 5.2.12 on 2026-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_solicitacaoativo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='conta_google',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='ativo',
            name='senha_conta_google',
            field=models.CharField(default=''),
        ),
    ]
