# Generated by Django 5.2.12 on 2026-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_ativo_conta_google_ativo_senha_conta_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
