# Generated by Django 5.2.12 on 2026-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_alter_ativo_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='conta_google',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='senha_conta_google',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
