from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('transporte/agendamento/', views.agendamento, name='agendamento'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agendar/', views.agendar, name='agendar'),
    path('api/eventos', views.listar_agendamentos, name='listar_agendamentos'),
    path('transporte/mudar_dia_agendamento/', views.mudar_dia_agendamento, name='mudar_dia_agendamento'),
    path('transporte/remover_agendamento/<int:pk>/', views.remover_agendamento, name='remover_agendamento'),
    path('transporte/veiculos/', views.veiculos, name='veiculos'),
    path('transporte/remover_veiculo/<int:pk>/', views.remover_veiculo, name='remover_veiculo'),
    path('transporte/editar_veiculo/<int:pk>/', views.editar_veiculo, name='editar_veiculo'),
    path('transporte/editar_agendamento/<int:pk>/', views.editar_agendamento, name='editar_agendamento'),
    path('transporte/viagens/', views.viagens, name='viagens'),
    path('transporte/historico/', views.historico, name='historico'),
    path('transporte/alterar_veiculo/<int:pk>/', views.alterar_veiculo, name='alterar_veiculo'),
    path('transporte/veiculos/tab/<str:aba>/<int:veiculo_id>/', views.carregar_aba, name='carregar_aba'),
    path('transporte/veiculos/salvar-aba-identificacao/<int:veiculo_id>/', views.salvar_aba_identificacao, name='salvar_aba_identificacao'),
    path('transporte/seguro_veiculo/<int:pk>/', views.seguro_veiculo, name='seguro_veiculo'),
    path('transporte/enviar/', views.enviar_texto, name='enviar_texto'),
    path('transporte/seguro_veiculo/<int:pk>/', views.upload_arquivos, name='upload_arquivos'),  
    path('transporte/comentarios/', views.comentarios, name='comentarios'),
    path('ativos/', views.ativos, name='ativos'),
    path('cadastrar_equipamento/', views.cadastrar_equipamento, name='cadastrar_equipamento'),
    path('listar_ativos/', views.listar_ativos, name='listar_ativos'),
    path('solicitar_equipamento/', views.solicitar_equipamento, name='solicitar_equipamento'),
    path('ver_solicitacoes/', views.ver_solicitacoes, name='ver_solicitacoes'),
    path('meus_itens/', views.meus_itens, name='meus_itens'),
    path('aprovar_solicitacao/<int:pk>/', views.aprovar_solicitacao, name='aprovar_solicitacao'),
    path('detalhes_ativo/<int:pk>/', views.detalhes_ativo, name='detalhes_ativo'),
    path('editar_ativo/<int:pk>/', views.editar_ativo, name='editar_ativo'),
    path('remover_ativo/<int:pk>/', views.remover_ativo, name='remover_ativo'),
    path('devolver_ativo/<int:pk>/', views.devolver_ativo, name='devolver_ativo'),
    path('transporte/menu_veiculos/', views.menu_veiculos, name="menu_veiculos"),
    path('historico_ativo/', views.historico_ativo, name='historico_ativo')
]  